config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'

  resources :home , path: "synchronous_shopping"

  # Routes API
  namespace :api do
    namespace :v1 do
      resources :synchronous_shoppings, path: "synchronous_shopping"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/synchronous_shopping.rb
class SynchronousShopping < ApplicationRecord
end

app/controllers/api/v1/synchronous_shoppings_controller.rb
class Api::V1::SynchronousShoppingsController < ApplicationController
  before_action :authorize_user, only: [:create]

  # GET /synchronous_shoppings
  def index
    # List data from data base
    @synchronous_shoppings = SynchronousShopping.where.not(roads: nil)
    render json: @synchronous_shoppings
  end

  # POST /synchronous_shoppings
  def create
    # Calling lib with synchronous_shopping logic and calculate
    result = SynchronousShoppingLogic.new(params).minimum_time

    # Only trsted params
    if params[:info].blank?
      @synchronous_shopping = SynchronousShopping.new(synchronous_shopping_params.merge(minimum_time: result))
    else
      @synchronous_shopping = SynchronousShopping.new(synchronous_shopping_params.merge(minimum_time: result, parameters: params[:info]))
    end

    # Validating saving
    if @synchronous_shopping.save
      render json: { minimum_time: result }
    else
      render json: @synchronous_shopping.errors, status: :unprocessable_entity
    end
  end

  private

  # Only allow a trusted parameter "white list" through
  def synchronous_shopping_params
    params.permit(:parameters, :shoping_centers, :roads, :username)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token

  # Method to ckeck user authorization
  def authorize_user
    UserAccess.check_user(params[:username], params[:checksum])
  rescue StandardError => e
    render json: { errors: e }, status: :unauthorized
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @synchronous_shoppings = SynchronousShopping.where(roads: nil)
  end

  def new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">TAXIMO TEST</a>

</nav>

<main class="container" role="main">
  <div class="jumbotron">
    <h1>Taximo Test - Synchronous Shopping </h1>
    <p class="lead">Se debe construir una aplicación web que solucione el problema para cada entrada de datos a
      través de una API. La aplicación debe estar construida en Javascript en el lado del servidor.
      Aunque el principal criterio de evaluación es que la aplicación funcione, la organización del
      código, la arquitectura usada y la documentación del código son importantes en la evaluación.</p>
    <%= link_to 'New Synchronous Shopping Test', new_home_path, class: 'btn btn-lg btn-success' %>
  </div>
  <div class="container"></div>
  <p class="lead">Resultados:</p>
  <div class="table-responsive">
    <table class="table table-bordered">
      <thead>
      <tr>
        <th scope="col">Parameters / Shopping Centers / Roads</th>
        <th scope="col">Minimun Time</th>
      </tr>
      </thead>
      <tbody>
      <% @synchronous_shoppings.each do |store| %>
        <tr>
          <th scope="row">
            <%= store.parameters %>
          </th>
          <td>
            <%= store.minimum_time %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <hr>
</main>
<div class="container">
  <div align="center">Desarrollado por Carlos A. Arboleda</div>
</div>

<br/><br/>

app/views/home/new.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="/synchronous_shopping">TAXIMO TEST</a>

</nav>

<main class="container" role="main">
  <div class="jumbotron">
    <h1>New Request</h1>

    <div class="form-group">
      <!--Form Text Area-->
      <textarea rows="10" cols="10" class="form-control" id="min_road_text_area"></textarea>
      <!--Button request-->
      <br/>
      <button class="btn btn-lg btn-success" onclick="synchronous_shopping()">
        Hacer Consulta
      </button>
    </div>
    <div class="result">
      <div class="min_time">
        <h2></h2>
        <h3></h3>
      </div>
    </div>

  </div>
</main>

<div class="container">
  <div align="center">Desarrollado por Carlos A. Arboleda</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taximo Test</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--Load all css and js three-->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--Check load Boostrap-->
    <link href="https://getbootstrap.com/docs/4.0/examples/jumbotron/jumbotron.css" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<p>Taximo Test developed by Carlos A. Arboleda :)</p>